drop table [dashui_starter].[dbo].[MasterCourierRates];


	CREATE TABLE [dashui_starter].[dbo].[MasterCourierRates] (
		Id INT PRIMARY KEY,
		MasterCourierPackageId INT Not NUll,
		MasterRateTypeId INT NOT NULL,
		MasterCourierShipmentType INT NOT NULL,
		zone_A DECIMAL(18,2) NULL,
		zone_B DECIMAL(18,2) NULL,
		zone_C DECIMAL(18,2) NULL,
		zone_D DECIMAL(18,2) NULL,
		zone_E DECIMAL(18,2) NULL,
		zone_F DECIMAL(18,2) NULL,
		zone_G DECIMAL(18,2) NULL,
		zone_H DECIMAL(18,2) NULL,
		zone_I DECIMAL(18,2) NULL,
		zone_J DECIMAL(18,2) NULL,
		zone_K DECIMAL(18,2) NULL,
		zone_L DECIMAL(18,2) NULL,
		zone_M DECIMAL(18,2) NULL,
		zone_N DECIMAL(18,2) NULL,
		zone_O DECIMAL(18,2) NULL,
		zone_P DECIMAL(18,2) NULL,
		zone_Q DECIMAL(18,2) NULL,
		zone_R DECIMAL(18,2) NULL,
		zone_S DECIMAL(18,2) NULL,
		zone_T DECIMAL(18,2) NULL,
		zone_U DECIMAL(18,2) NULL,
		zone_V DECIMAL(18,2) NULL,
		zone_W DECIMAL(18,2) NULL,
		zone_X DECIMAL(18,2) NULL,
		zone_Y DECIMAL(18,2) NULL,
		zone_Z DECIMAL(18,2) NULL,
		created_at DATETIME DEFAULT GETDATE() NULL,
		updated_at DATETIME DEFAULT GETDATE() NULL,
		deleted_at DATETIME NULL
	);
